version: '3.3'
services:

  nginx:
    image: nginx:1.21.5
    container_name: ivosights-rizki-nginx
    restart: unless-stopped
    ports:
      - 8080:80
      - 9090:8080
    volumes:
      - ../code/be:/var/www/html/be
      - ../code/fe:/var/www/html/fe
      - ./configs/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  mariadb:
    image: mariadb:10.10
    container_name: ivosights-rizki-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: ivosights
      MARIADB_PASSWORD: ivosights
      MARIADB_DATABASE: db_project_rizki
    volumes:
      - ./volumes/data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./images/php/Dockerfile
    image: phpcomposer:ivosights
    container_name: ivosights-rizki-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../code/be:/var/www/html/be
      - ../code/fe:/var/www/html/fe
      - ./configs/phpcomposer/php.ini:/usr/local/etc/php/php.ini
      - ./configs/phpcomposer/workers.conf:/etc/supervisor/conf.d/workers.conf
    command: >
      sh -c "cd fe &&
             yarn add @vue/cli &&
             yarn add @vue/cli-service &&
             yarn install &&
             yarn build &&
             cd ../be &&
             composer install &&
             yarn install &&
             chmod -R 777 storage/logs/ &&
             chmod -R 777 storage/framework/sessions/ &&
             chmod -R 777 storage/framework/views/ &&
             chmod -R 777 storage/framework/cache/ &&
             chmod -R 777 storage/app/public/ &&
             php artisan route:clear &&
             php artisan cache:clear &&
             php artisan config:clear &&
             php artisan view:clear &&
             php artisan view:clear &&
             php artisan key:generate &&
             php artisan migrate &&
             php-fpm"
